# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      # - run: npm ci
      # - run: npm run build --if-present
      - run: npm install
      - run: npm test
        env:
          TEST_TOKEN: TEST_TOKEN # Environment variable
          API_ACCESS_KEY: ${{secrets.API_ACCESS_KEY}} # Environment variable
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} # Environment variable
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Environment variable

      - name: "Configure AWS Credentials" Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Specify the region of your S3 bucket

      - name: Upload files to S3
        run: |
          aws s3 sync ./ s3://krfnodeserver/ --delete
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
